services:
  pfm:
    image: "ruby:3.3.6"
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    command: "sh -c 'bundle install && rake db:migrate && rails server -b 0.0.0.0'"
    restart: always
