# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78d414d92e61e95aee06909a2d4255c4597de3c9618d9e5f8e19bdb6b88e0d00ed2dc707d06fcce2788fa8284ca44320e1f08924a402a113bf2acce66f572af2

test:
  secret_key_base: 4b886cd5880a10eb8b8e09a2417de01ae17ef153343ed2c950b93f10a1f55960cfa299e5addfdcf484b0db8cecf85c4479166a34d6b9823ab87e023f8934e194

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
